// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxcxrbcmsgmfehcieljf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4Y3hyYmNtc2dtZmVoY2llbGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzU4ODYsImV4cCI6MjA2NDY1MTg4Nn0.XXyRBOPTqdOzaeW2gikZV5UGXU13OfjMQi7qkBlSESs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);